CREATE TABLE IF NOT EXISTS "Bid" (
	"id"			INTEGER NOT NULL UNIQUE,
	"amount"		INTEGER NOT NULL,
	"auction_id" 	INTEGER NOT NULL,
	"user_id"		INTEGER NOT NULL,
	"message"		TEXT NOT NULL DEFAULT '',
	PRIMARY KEY("id" AUTOINCREMENT)
);
