CREATE TABLE IF NOT EXISTS "Image" (
	"id"			INTEGER NOT NULL UNIQUE,
	"auction_id"	INTEGER NOT NULL,
	"image_order"	INTEGER NOT NULL DEFAULT 0,
	"url"			TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
