CREATE TABLE IF NOT EXISTS "Role" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"color"	INTEGER NOT NULL DEFAULT 16777215,
	"flags"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
