CREATE TABLE IF NOT EXISTS "Role" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	"color"	TEXT NOT NULL DEFAULT "#ffffff",
	"flags"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
