# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "sinatra"
gem "sinatra-reloader"
gem "sqlite3"
gem "slim"
gem "sassc"
gem "colorize"
gem "bcrypt"

gem "rmagick", "~> 4.2"

gem "sinatra-flash", "~> 0.3.0"

gem "fileutils", "~> 1.6"

gem "webrick", "~> 1.7"
